module.exports = [{"QTY":1,"NAME":"mediterranean avenue","TYPE ":"property","VALUE":1,"COLOR_A":"brown","PROP_A":[1,2],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"baltic avenue","TYPE ":"property","VALUE":1,"COLOR_A":"brown","PROP_A":[1,2],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"water works","TYPE ":"property","VALUE":2,"COLOR_A":"l_green","PROP_A":[1,2],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"electric company","TYPE ":"property","VALUE":2,"COLOR_A":"l_green","PROP_A":[1.2],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"oriental avenue","TYPE ":"property","VALUE":1,"COLOR_A":"l_blue","PROP_A":[1,2,3],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"vermont avenue","TYPE ":"property","VALUE":1,"COLOR_A":"l_blue","PROP_A":[1,2,3],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"connecticut avenue","TYPE ":"property","VALUE":1,"COLOR_A":"l_blue","PROP_A":[1,2,3],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"north carolina avenue","TYPE ":"property","VALUE":4,"COLOR_A":"green","PROP_A":[2,4,7],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"pennsylvania avenue","TYPE ":"property","VALUE":4,"COLOR_A":"green","PROP_A":[2,4,7],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"pacific avenue","TYPE ":"property","VALUE":4,"COLOR_A":"green","PROP_A":[2,4,7],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"new york avenue","TYPE ":"property","VALUE":2,"COLOR_A":"orange","PROP_A":[1,3,5],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"st. james place","TYPE ":"property","VALUE":2,"COLOR_A":"orange","PROP_A":[1,3,5],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"tennessee avenue","TYPE ":"property","VALUE":2,"COLOR_A":"orange","PROP_A":[1,3,5],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"atlantic avenue","TYPE ":"property","VALUE":3,"COLOR_A":"yellow","PROP_A":[2,4,6],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"marvin gardens","TYPE ":"property","VALUE":3,"COLOR_A":"yellow","PROP_A":[2,4,6],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"ventnor avenue","TYPE ":"property","VALUE":3,"COLOR_A":"yellow","PROP_A":[2,4,6],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"states avenue","TYPE ":"property","VALUE":2,"COLOR_A":"pink","PROP_A":[1,2,4],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"st. charles place","TYPE ":"property","VALUE":2,"COLOR_A":"pink","PROP_A":[1,2,4],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"virginia avenue","TYPE ":"property","VALUE":2,"COLOR_A":"pink","PROP_A":[1,2,4],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"kentucky avenue","TYPE ":"property","VALUE":3,"COLOR_A":"red","PROP_A":[2,3,6],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"indiana avenue","TYPE ":"property","VALUE":3,"COLOR_A":"red","PROP_A":[2,3,6],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"illinois avenue","TYPE ":"property","VALUE":3,"COLOR_A":"red","PROP_A":[2,3,6],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"park place","TYPE ":"property","VALUE":4,"COLOR_A":"blue","PROP_A":[3,8],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"boardwalk","TYPE ":"property","VALUE":4,"COLOR_A":"blue","PROP_A":[3,8],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"pennsylvania railroad","TYPE ":"property","VALUE":2,"COLOR_A":"black","PROP_A":[1,2,3,4],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"short line","TYPE ":"property","VALUE":2,"COLOR_A":"black","PROP_A":[1,2,3,4],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"reading railroad","TYPE ":"property","VALUE":2,"COLOR_A":"black","PROP_A":[1,2,3,4],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"b. & o. railroad","TYPE ":"property","VALUE":2,"COLOR_A":"black","PROP_A":[1,2,3,4],"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":2,"NAME":"property wild card","TYPE ":"property","VALUE":null,"COLOR_A":"all","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"property wild card","TYPE ":"property","VALUE":2,"COLOR_A":"black","PROP_A":[1,2,3,4],"COLOR_B":"l_green","PROP_B":[1,2],"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"property wild card","TYPE ":"property","VALUE":4,"COLOR_A":"l_blue","PROP_A":[1,2,3],"COLOR_B":"black","PROP_B":[1,2,3,4],"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"property wild card","TYPE ":"property","VALUE":4,"COLOR_A":"green","PROP_A":[2,4,7],"COLOR_B":"black","PROP_B":[1,2,3,4],"TARGET":null,"DESC":null,"SUB":null},
{"QTY":2,"NAME":"property wild card","TYPE ":"property","VALUE":3,"COLOR_A":"red","PROP_A":[2,3,6],"COLOR_B":"yellow","PROP_B":[2,4,6],"TARGET":null,"DESC":null,"SUB":null},
{"QTY":2,"NAME":"property wild card","TYPE ":"property","VALUE":2,"COLOR_A":"pink","PROP_A":[1,2,4],"COLOR_B":"orange","PROP_B":[1,3,5],"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"property wild card","TYPE ":"property","VALUE":4,"COLOR_A":"green","PROP_A":[2,4,7],"COLOR_B":"blue","PROP_B":[3.8],"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":"property wild card","TYPE ":"property","VALUE":1,"COLOR_A":"l_blue","PROP_A":[1,2,3],"COLOR_B":"brown","PROP_B":[1,2],"TARGET":null,"DESC":null,"SUB":null},
{"QTY":3,"NAME":"house","TYPE ":"action","VALUE":3,"COLOR_A":"l_green","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"self","DESC":"Add onto any full set you own to add <value> to the Rent value.","SUB":"(Except Railroads and Utilities)"},
{"QTY":2,"NAME":"hotel","TYPE ":"action","VALUE":4,"COLOR_A":"l_blue","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"self","DESC":"Add onto any full set you own to add <value> to the Rent value.","SUB":"(Except Railroads and Utilities)"},
{"QTY":6,"NAME":null,"TYPE ":"currency","VALUE":1,"COLOR_A":"l_yellow","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":5,"NAME":null,"TYPE ":"currency","VALUE":2,"COLOR_A":"l_pink","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":3,"NAME":null,"TYPE ":"currency","VALUE":3,"COLOR_A":"l_green","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":3,"NAME":null,"TYPE ":"currency","VALUE":4,"COLOR_A":"l_blue","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":2,"NAME":null,"TYPE ":"currency","VALUE":5,"COLOR_A":"purple","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":1,"NAME":null,"TYPE ":"currency","VALUE":10,"COLOR_A":"orange","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":null,"DESC":null,"SUB":null},
{"QTY":3,"NAME":"forced deal","TYPE ":"action","VALUE":3,"COLOR_A":"l_green","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"1","DESC":"Swap any property with another player.","SUB":"(Cannot be part of a full set.)"},
{"QTY":3,"NAME":"sly deal","TYPE ":"action","VALUE":3,"COLOR_A":"l_green","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"1","DESC":"Steal a property from the player of your choice.","SUB":"(Cannot be part of a full set.)"},
{"QTY":3,"NAME":"debt collector","TYPE ":"action","VALUE":3,"COLOR_A":"l_green","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"1","DESC":"Force any player to pay you 5m.","SUB":null},
{"QTY":2,"NAME":"deal breaker","TYPE ":"action","VALUE":5,"COLOR_A":"purple","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"1","DESC":"Steal a complete set of properties from any player.","SUB":"(Includes any buildings.)"},
{"QTY":3,"NAME":"just say no!","TYPE ":"action","VALUE":4,"COLOR_A":"l_blue","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"1","DESC":"Use any time when an Action card is played against you.","SUB":null},
{"QTY":2,"NAME":"double the rent!","TYPE ":"action","VALUE":1,"COLOR_A":"l_yellow","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"self","DESC":"Needs to be played with a Rent card.","SUB":null},
{"QTY":3,"NAME":"rent","TYPE ":"action","VALUE":3,"COLOR_A":"all","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"1","DESC":"Force one player to pay you rent for properties of any single color.","SUB":null},
{"QTY":2,"NAME":"rent","TYPE ":"action","VALUE":1,"COLOR_A":"black","PROP_A":null,"COLOR_B":"l_green","PROP_B":null,"TARGET":"all","DESC":"All players pay you rent for properties you own in one of these colors.","SUB":null},
{"QTY":2,"NAME":"rent","TYPE ":"action","VALUE":1,"COLOR_A":"brown","PROP_A":null,"COLOR_B":"l_blue","PROP_B":null,"TARGET":"all","DESC":"All players pay you rent for properties you own in one of these colors.","SUB":null},
{"QTY":2,"NAME":"rent","TYPE ":"action","VALUE":1,"COLOR_A":"green","PROP_A":null,"COLOR_B":"blue","PROP_B":null,"TARGET":"all","DESC":"All players pay you rent for properties you own in one of these colors.","SUB":null},
{"QTY":2,"NAME":"rent","TYPE ":"action","VALUE":1,"COLOR_A":"red","PROP_A":null,"COLOR_B":"yellow","PROP_B":null,"TARGET":"all","DESC":"All players pay you rent for properties you own in one of these colors.","SUB":null},
{"QTY":2,"NAME":"rent","TYPE ":"action","VALUE":1,"COLOR_A":"pink","PROP_A":null,"COLOR_B":"orange","PROP_B":null,"TARGET":"all","DESC":"All players pay you rent for properties you own in one of these colors.","SUB":null},
{"QTY":3,"NAME":"it's my birthday","TYPE ":"action","VALUE":2,"COLOR_A":"l_pink","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"all","DESC":"All players give you 2M as a gift.","SUB":null},
{"QTY":10,"NAME":"draw two","TYPE ":"action","VALUE":1,"COLOR_A":"l_yellow","PROP_A":null,"COLOR_B":null,"PROP_B":null,"TARGET":"self","DESC":"Draw 2 exra cards.","SUB":null}];